### ISSUE TITLE
TRestRawSignalAddNoiseProcess not working correctly near limits

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/rawlib#113]
When the noise would take the point value to outside of the limits of the numeric type (short) undefined behaviour takes place and the signal is broken. This should be handled properly.

**Comment by jgalan** [comment]
It is not the noise process that needs to be fixed, right? I would say that the methods that allow to add a point into the `TRestRawSignal` should check the value and if it is not inside the bounds, then just assign the maximum value, as if the pulse would be saturating. It is this the strategy you plan to follow at the PR #114?
