### ISSUE TITLE
TRestRawMultiFEMINOSToSignalProcess exits when processing the last event of a stopped run .aqs file

### ISSUE THREAD

**Issue by AlvaroEzq** [rest-for-physics/rawlib#135]
We have being dealing with this issue where this process TRestRawMultiFEMINOSToSignalProcess exits when processing the last event of a stopped (with ctrl+C) run .aqs file and then, the output file cannot be further processed. This is a very annoying problem because is very common to stop the run due to a trip or whatever but still want to analyze the events.

I found that the line causing this issue is this one:
https://github.com/rest-for-physics/rawlib/blob/1137fdec3cfe42cb3b42b9612535efe2355e93bf/src/TRestRawMultiFEMINOSToSignalProcess.cxx#L366
And changing it to `return nullptr;` works for me to solve this specific case.

I am not familiar with this kind of processes so I am not sure if this change would break in other scenarios...

**Comment by jgalan** [comment]
At first sight it looks as a good solution, there is the TREX-DM validation pipeline that uses this process, so in case that this line causes troubles the validation might fail.

https://github.com/rest-for-physics/framework/actions/runs/9300876077/job/25598296562

Just push a PR with this change and check if passes the pipeline.

**Comment by AlvaroEzq** [comment]
Solved in [PR#136](https://github.com/rest-for-physics/rawlib/pull/136).
