### ISSUE TITLE
Recover TRestFFT from quarantine, and migrate to TRestRawFFT

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/rawlib#4]
TRestFFT is an interface to fftw library including some common methods to apply filters or perform other operations in the frequential domain.

TRestFFT was operating on a TRestSignalEvent which was not the most convenient. After the production of `TRestRawSignalEvent` this new fixed binning data type is much more convenient. Still there is some work to translate this class to be operative again.

**Comment by jgalan** [comment]
I guess this issue was already addressed, since @DavidDiezIb recovered the `TRestFFT` already?

**Comment by DavidDiezIb** [comment]
Yes, sorry, I forgot tag the issue in the corresponding commit. I updated it to v2.3 here: a2324601268910b3130a4111963084a1cf7b652e
