### ISSUE TITLE
TRestRawVetoAnalysisProcess update

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/rawlib#6]
This process needs to be upgraded to adopt a more sophisticated observable definition to be used later in our analysis work.

For the moment this process is already accepting an arbitrary number of daq channel ids to be passed through a metadata member, `fSignalIds`. The process will remove from the `TRestRawSignalEvent` all the VETO signals defined in the process metadata as for example: `<parameter name="vetoSignalId" value="12,89,189"/>`.

However, as it is now, only the last VETO signal id will be used to define the observables.

We might think of different solutions that could be developed, from easier to harder levels of implementation difficulty:

1. We define a unique observable with the average peak time, and average amplitude or integral. For example, `PeakTimeAverage` and `MaxPeakIntegral` using all the signal ids provided.
2. We create an observable for each channel. Therefore, we construct the observable name internally using the VETO data ids provided. I.e. `PeakTime_12`, `PeakTime_89`, ...
3. We define a more sophisticated system to group veto signal ids and create grouped observables. For example:

We could imagine the following possible RML metadata definitions:

```
<TRestRawVetoAnalysisProcess ...>
    <vetoGroup name="top" daqIds="12,89`/>
    <vetoGroup name="189" daqIds="189" />
</TRestRawVetoAnalysisProcess>
```

This last definition could re-group solution 1 and 2 into one.

Since if we have only one signal we will get an observable named `PeakTime_189`, and if we use several ids this will become `PeakTime_top`.

**Comment by KonradAltenmueller** [comment]
Yes, I am working on this at the moment. Currently I generate an observable for each veto. I think taking the averages for the peak amplitude is not so good, because the vetoes have different gains. Also it is probably best to keep as much of the information from the veto signals accessible.

**Comment by jgalan** [comment]
> Yes, I am working on this at the moment. Currently I generate an observable for each veto. I think taking the averages for the peak amplitude is not so good, because the vetoes have different gains. Also it is probably best to keep as much of the information from the veto signals accessible.

Ok, I guess then, a potential approach is to use a unique `std::map` observable that registers the daq id together with the amplitude and peak time in the same fashion as it is done for example for `max_amplitude_map` at `TRestRawSignalAnalysisProcess`. I believe that would simplify the implementation of the process.

**Comment by jgalan** [comment]
Related also to discussion

http://ezpc10.unizar.es/t/is-there-something-like-a-vector-of-tixmlelements/431/3

**Comment by KonradAltenmueller** [comment]
One more thing: currently, if in an event there is a signal in the veto, only this signal is deleted from the output, but all other signals in the same event are kept. This doesn't make sense to me... Shouldn't all signals from the event be deleted?

I think it was already like this before I started to work on this process, so it seemed to work for the CAST analysis, which confuses me.
Or am I missing the point how the veto process should work?

**Comment by cmargalejo** [comment]
Hello Konrad,
As I understand it, we keep the other signals so that we can see the event in the micromegas and characterize it. As you say, the event is caused by a muon so it has to be removed. So we remove it later by applying the muon veto cut, which in CAST in particular is that we remove the event if there is an event in the veto with veto peak time between 100 and 300, and with amplitude > 200.
I suppose we could also do what you say, but we would be losing information, no?

**Comment by KonradAltenmueller** [comment]
Hi Cristina,
ok, then it makes sense. Yes, it is better to keep this information, I will leave this part like it is. 
I also implemented the option to set a threshold for the vetoes, but this is then not really necessary...

**Comment by jgalan** [comment]
Yes, simply the idea is that the `TRestVetoAnalysisProcess` extracts the information from the veto signals, and then it lets the event data `TRestRawSignalEvent` in the same state it would be as if there would be no VETO so that the analysis and further processes continue independently of the case that the veto analysis process says it is a VETO. This is a later analysis, as Cristina said. We will just get all the information at the analysis tree.

**Comment by KonradAltenmueller** [comment]
With the latest commit, you can define veto groups with XML blocks like for example 
`<vetoGroup name = "top" signalIDs="1,2,3">
 <vetoGroup name = "front" signalIDs="4,5,6,7">`
 
 This then generates observables like `veto_MaxPeakAmplitude_top` and `veto_MaxPeakAmplitude_front` (and the same for peak times), each containing a map with <signal ID , value>.
