### ISSUE TITLE
TRestMultiFEMINOSToSignalProcess fails in the construction of TRestRawSignalEvent

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/rawlib#7]
For some strange reason when this process splits what should be a single event into two independent events.

What it is observed is that all the pulses except one are registered in one `TRestRawSignalEvent`, the next event is created with the same event ID, and it contains only one single pulse that corresponds always to the same signal ID from the 9 veto signals used.

A sample file for testing has been placed here, with tag `BackgroundWith9Vetos`: https://sultan.unizar.es/exchange/

Some discussions about the problem already took place at the forum with @DavidDiezIb and @cmargalejo: http://ezpc10.unizar.es/t/same-id-for-two-consecutive-events-and-splitted-events/422

What is the hardware configuration that produces this problem? Is single Feminos, or TCM is involved? Where are connected the VETO signals?

**Comment by KonradAltenmueller** [comment]
Problem was caused by a wrong Feminos configuration
