### ISSUE TITLE
Problems adding a new process

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/rawlib#78]
I have created a new process called `TRestRawSignalRangeReductionProcess` on branch [`lobis-range-reduction`](https://github.com/rest-for-physics/rawlib/pull/76) (commit 76a090d6f45a5365bcd2dfecacac5e92ebd49a19 can be used as reference).

I think I created the process correctly following the guidelines, using another process as reference.

However the process doesn't seem to be recognized. I cannot use it on `restManager` or access it from `restRoot`.

Perhaps its a silly mistake but I have been unable to find it. Maybe its related to https://github.com/rest-for-physics/rawlib/issues/74.

Using the below code you can generate a rest installation to reproduce this problem:

```
cd /tmp
git clone https://github.com/rest-for-physics/framework.git
cd framework
python3 pull-submodules.py --latest
cd source/libraries/raw
git checkout 76a090d6f45a5365bcd2dfecacac5e92ebd49a19
cd ../../..
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/rest-test -DREST_ALL_LIBS=ON
make install -j
source /tmp/rest-test/thisREST.sh
restRoot
```

```
root [0] TRestRawSignalRangeReductionProcess()
input_line_196:2:3: error: use of undeclared identifier 'TRestRawSignalRangeReductionProcess'
 (TRestRawSignalRangeReductionProcess())
  ^
Error in <HandleInterpreterException>: Error evaluating expression (TRestRawSignalRangeReductionProcess()).
Execution of your code was aborted.
root [1]
```

**Comment by jgalan** [comment]
There is a branch or PR associated?

**Comment by lobis** [comment]
> There is a branch or PR associated?

https://github.com/rest-for-physics/rawlib/pull/76

**Comment by jgalan** [comment]
The process source filename extension should be `.cxx` while you named it `.cpp`. That must be the main reason, the source is not added for compilation by the cmake system

**Comment by lobis** [comment]
> The process source filename extension should be `.cxx` while you named it `.cpp`. That must be the main reason, the source is not added for compilation by the cmake system

🤦🏻 thanks I have spent an embarrasing amount of time on this.

**Comment by jgalan** [comment]
I found out because when I was doing `make` it did not appear in the list of installed headers
