### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by KonradAltenmueller** [rest-for-physics/rawlib#8]
REST doesn't compile anymore after updating the raw library from bfcb7d6 to e78464d:

```
[ 75%] Built target RestTrack
make[2]: *** No hay ninguna regla para construir el objetivo '../source/libraries/raw/inc/TRestRawSignalToSignalProcess.h', necesario para 'rootdict/CINT_TRestRawSignalToSignalProcess.cxx'.  Alto.
CMakeFiles/Makefile2:368: fallo en las instrucciones para el objetivo 'source/libraries/raw/CMakeFiles/RestRaw.dir/all'
make[1]: *** [source/libraries/raw/CMakeFiles/RestRaw.dir/all] Error 2
Makefile:129: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

```

**Comment by jgalan** [comment]
Hi Konrad,

the latest pipelines at `framework` and `rawlib` repositories seem they are compiling properly.

https://lfna.unizar.es/rest-for-physics/framework/-/commit/742795ba5d38866cf193488e15557643741ec897

https://lfna.unizar.es/rest-for-physics/rawlib/-/commit/062cb9dde573a9c6203c8d2eab740d84ea071930

The `TRestRawSignalToSignalProcess` now belongs to the `connectors` library. So, probably you are not in a clean state.

If you have pushed all relevant changes to the remote repositories, and you dont have local changes you could be losing, then it is safe to execute

```
source clean-state.sh
```

**Comment by KonradAltenmueller** [comment]
Yes, it works after getting the clean state agin. A bit strange, because I already restored the clean state earlier before pushing my commit...

**Comment by jgalan** [comment]
Strange, yes. just in case a reminder. In principle when you use `clean-state.sh` you get back to a state where the reference to `rawlib` is the official one. So you need to go to `source/libraries/raw/` and do `git checkout master` ^ `git pull` to be again in the latest state of development ar `rawlib`.
